"""Balatro joker library - 150 jokers with IDs, names, costs, and effect descriptions."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class JokerInfo:
    id: int
    name: str
    base_cost: int  # 0 = legendary / not buyable in shop
    effect: str
    rarity: str = "Common"  # Common, Uncommon, Rare, Legendary


JOKER_LIBRARY: List[JokerInfo] = [
    JokerInfo(1, "Joker", 2, "+4 Mult"),
    JokerInfo(2, "Greedy Joker", 5, "Played cards with Diamond suit give +3 Mult"),
    JokerInfo(3, "Lusty Joker", 5, "Played cards with Heart suit give +3 Mult"),
    JokerInfo(4, "Wrathful Joker", 5, "Played cards with Spade suit give +3 Mult"),
    JokerInfo(5, "Gluttonous Joker", 5, "Played cards with Club suit give +3 Mult"),
    JokerInfo(6, "Jolly Joker", 3, "+8 Mult if hand contains a Pair"),
    JokerInfo(7, "Zany Joker", 4, "+12 Mult if hand contains Three of a Kind"),
    JokerInfo(8, "Mad Joker", 4, "+10 Mult if hand contains Two Pair"),
    JokerInfo(9, "Crazy Joker", 4, "+12 Mult if hand contains Straight"),
    JokerInfo(10, "Droll Joker", 4, "+10 Mult if hand contains Flush"),
    JokerInfo(11, "Sly Joker", 3, "+50 Chips if hand contains a Pair"),
    JokerInfo(12, "Wily Joker", 4, "+100 Chips if hand contains Three of a Kind"),
    JokerInfo(13, "Clever Joker", 4, "+80 Chips if hand contains Two Pair"),
    JokerInfo(14, "Devious Joker", 4, "+100 Chips if hand contains Straight"),
    JokerInfo(15, "Crafty Joker", 4, "+80 Chips if hand contains Flush"),
    JokerInfo(16, "Half Joker", 5, "+20 Mult if played hand contains 3 or fewer cards"),
    JokerInfo(17, "Joker Stencil", 8, "X1 Mult for each empty joker slot", "Uncommon"),
    JokerInfo(18, "Four Fingers", 7, "All Flushes and Straights can be made with 4 cards", "Uncommon"),
    JokerInfo(19, "Mime", 5, "Retrigger all card held in hand abilities", "Uncommon"),
    JokerInfo(20, "Credit Card", 1, "Go up to -$20 in debt"),
    JokerInfo(21, "Ceremonial Dagger", 6, "Sacrifice joker to right, gain double its sell value as +Mult", "Uncommon"),
    JokerInfo(22, "Banner", 5, "+30 Chips for each remaining discard"),
    JokerInfo(23, "Mystic Summit", 5, "+15 Mult when 0 discards remaining"),
    JokerInfo(24, "Marble Joker", 6, "Adds one Stone card to deck when Blind is selected", "Uncommon"),
    JokerInfo(25, "Loyalty Card", 5, "X4 Mult every 6 hands played", "Uncommon"),
    JokerInfo(26, "8 Ball", 5, "1 in 4 chance to create a Tarot card when any played 8 is scored"),
    JokerInfo(27, "Misprint", 4, "+0-23 Mult"),
    JokerInfo(28, "Dusk", 5, "Retrigger all played cards in final hand of round", "Uncommon"),
    JokerInfo(29, "Raised Fist", 5, "Adds double the rank of lowest card held in hand to Mult"),
    JokerInfo(30, "Chaos the Clown", 4, "1 free reroll per shop"),
    JokerInfo(31, "Fibonacci", 8, "+8 Mult for each Ace, 2, 3, 5, or 8 scored", "Uncommon"),
    JokerInfo(32, "Steel Joker", 7, "X0.2 Mult for each Steel card in your full deck", "Uncommon"),
    JokerInfo(33, "Scary Face", 4, "Played face cards give +30 Chips when scored"),
    JokerInfo(34, "Abstract Joker", 4, "+3 Mult for each Joker card"),
    JokerInfo(35, "Delayed Gratification", 4, "Earn $2 per discard if no discards are used by end of round"),
    JokerInfo(36, "Hack", 6, "Retrigger each played 2, 3, 4, or 5", "Uncommon"),
    JokerInfo(37, "Pareidolia", 5, "All cards are considered face cards", "Uncommon"),
    JokerInfo(38, "Gros Michel", 5, "+15 Mult, 1 in 6 chance this card is destroyed at end of round"),
    JokerInfo(39, "Even Steven", 4, "Played cards with even rank give +4 Mult when scored"),
    JokerInfo(40, "Odd Todd", 4, "Played cards with odd rank give +31 Chips when scored"),
    JokerInfo(41, "Scholar", 4, "Played Aces give +20 Chips and +4 Mult when scored"),
    JokerInfo(42, "Business Card", 4, "Played face cards have a 1 in 2 chance to give $2 when scored"),
    JokerInfo(43, "Supernova", 5, "Adds the number of times poker hand has been played to Mult"),
    JokerInfo(44, "Ride the Bus", 6, "+1 Mult per consecutive hand played without a scoring face card. Resets if face card scored."),
    JokerInfo(45, "Space Joker", 5, "1 in 4 chance to upgrade level of played poker hand", "Uncommon"),
    JokerInfo(46, "Egg", 4, "Earns $3 of sell value at end of each round"),
    JokerInfo(47, "Burglar", 6, "When Blind is selected, gain +3 Hands and lose all discards", "Uncommon"),
    JokerInfo(48, "Blackboard", 6, "X3 Mult if all cards held in hand are Spades or Clubs", "Uncommon"),
    JokerInfo(49, "Runner", 5, "Gains +15 Chips if played hand contains a Straight"),
    JokerInfo(50, "Ice Cream", 5, "+100 Chips, -5 Chips for every hand played"),
    JokerInfo(51, "DNA", 8, "If first hand of round has only 1 card, add a permanent copy to deck", "Rare"),
    JokerInfo(52, "Splash", 3, "Every played card counts in scoring"),
    JokerInfo(53, "Blue Joker", 5, "+2 Chips for each remaining card in deck"),
    JokerInfo(54, "Sixth Sense", 6, "If first hand is a single 6, destroy it and create a Spectral card", "Uncommon"),
    JokerInfo(55, "Constellation", 6, "Gains X0.1 Mult every time a Planet card is used", "Uncommon"),
    JokerInfo(56, "Hiker", 5, "Every playing card scored permanently gains +5 Chips", "Uncommon"),
    JokerInfo(57, "Faceless Joker", 4, "Earn $5 if 3 or more face cards are discarded at once"),
    JokerInfo(58, "Green Joker", 4, "+1 Mult per hand played, -1 Mult per discard"),
    JokerInfo(59, "Superposition", 4, "Create a Tarot card if poker hand contains an Ace and a Straight"),
    JokerInfo(60, "To Do List", 4, "Earn $4 if poker hand type matches the randomly selected one"),
    JokerInfo(61, "Cavendish", 4, "X3 Mult, 1 in 1000 chance this card is destroyed at end of round"),
    JokerInfo(62, "Card Sharp", 6, "X3 Mult if played poker hand has already been played this round", "Uncommon"),
    JokerInfo(63, "Red Card", 5, "Gains +3 Mult when any Booster Pack is skipped"),
    JokerInfo(64, "Madness", 7, "X0.5 Mult, when Small or Big Blind is selected, destroy a random Joker", "Uncommon"),
    JokerInfo(65, "Square Joker", 4, "+4 Chips if played hand has exactly 4 cards"),
    JokerInfo(66, "Seance", 6, "If poker hand is a Straight Flush, create a Spectral card", "Uncommon"),
    JokerInfo(67, "Riff-Raff", 6, "When Blind is selected, create 2 Common Jokers"),
    JokerInfo(68, "Vampire", 7, "Gains X0.1 Mult for each Enhanced card played. Removes enhancement.", "Uncommon"),
    JokerInfo(69, "Shortcut", 7, "Allows Straights to be made with gaps of 1 rank", "Uncommon"),
    JokerInfo(70, "Hologram", 7, "Gains X0.25 Mult every time a playing card is added to your deck", "Uncommon"),
    JokerInfo(71, "Vagabond", 8, "Create a Tarot card if hand is played with $4 or less", "Rare"),
    JokerInfo(72, "Baron", 8, "Each King held in hand gives X1.5 Mult", "Rare"),
    JokerInfo(73, "Cloud 9", 7, "Earn $1 for each 9 in your full deck at end of round", "Uncommon"),
    JokerInfo(74, "Rocket", 6, "Earns $2 at end of round, payout increases by $2 when Boss Blind is defeated"),
    JokerInfo(75, "Obelisk", 8, "X0.2 Mult per consecutive hand played that is not your most played poker hand", "Rare"),
    JokerInfo(76, "Midas Mask", 7, "All face cards become Gold cards when played", "Uncommon"),
    JokerInfo(77, "Luchador", 5, "Sell this card to disable the current Boss Blind", "Uncommon"),
    JokerInfo(78, "Photograph", 5, "First played face card gives X2 Mult when scored"),
    JokerInfo(79, "Gift Card", 6, "Add $1 of sell value to every Joker at end of round", "Uncommon"),
    JokerInfo(80, "Turtle Bean", 6, "+5 Hand Size, reduces by 1 each round"),
    JokerInfo(81, "Erosion", 6, "+4 Mult for each card below 52 in your full deck", "Uncommon"),
    JokerInfo(82, "Reserved Parking", 6, "Each hand played with a face card held gives a 1 in 2 chance of $1"),
    JokerInfo(83, "Mail-In Rebate", 4, "Earn $5 when you discard a single card that matches the randomly selected rank"),
    JokerInfo(84, "To the Moon", 5, "Earn an extra $1 of interest for every $5 you have at end of round", "Uncommon"),
    JokerInfo(85, "Hallucination", 4, "1 in 2 chance to create a Tarot card when any Booster Pack is opened"),
    JokerInfo(86, "Fortune Teller", 6, "+1 Mult for each Tarot card used this run"),
    JokerInfo(87, "Juggler", 4, "+1 hand size"),
    JokerInfo(88, "Drunkard", 4, "+1 discard per round"),
    JokerInfo(89, "Stone Joker", 6, "+25 Chips for each Stone card in your full deck", "Uncommon"),
    JokerInfo(90, "Golden Joker", 6, "Earn $4 at end of round"),
    JokerInfo(91, "Lucky Cat", 6, "Gains X0.25 Mult every time a Lucky card triggers", "Uncommon"),
    JokerInfo(92, "Baseball Card", 8, "Uncommon Jokers each give X1.5 Mult", "Rare"),
    JokerInfo(93, "Bull", 6, "+2 Chips for each dollar you have"),
    JokerInfo(94, "Diet Cola", 6, "Sell to create a free Double Tag"),
    JokerInfo(95, "Trading Card", 6, "If first discard of round has only 1 card, destroy it and earn $3", "Uncommon"),
    JokerInfo(96, "Flash Card", 5, "Gains +2 Mult when you reroll the shop"),
    JokerInfo(97, "Popcorn", 5, "+20 Mult, -4 Mult per round played"),
    JokerInfo(98, "Spare Trousers", 6, "Gains +2 Mult if played hand contains Two Pair", "Uncommon"),
    JokerInfo(99, "Ancient Joker", 8, "X1.5 Mult for each distinct suit amongst played cards", "Rare"),
    JokerInfo(100, "Ramen", 6, "X2 Mult, loses X0.01 Mult per card discarded", "Uncommon"),
    JokerInfo(101, "Walkie Talkie", 4, "Each played 10 or 4 gives +10 Chips and +4 Mult"),
    JokerInfo(102, "Seltzer", 6, "Retrigger all cards played for the next 10 hands played", "Uncommon"),
    JokerInfo(103, "Castle", 6, "Gains +3 Chips per discarded card of the randomly selected suit", "Uncommon"),
    JokerInfo(104, "Smiley Face", 4, "Played face cards give +5 Mult when scored"),
    JokerInfo(105, "Campfire", 9, "X0.25 Mult for each card sold, resets when Boss Blind is defeated", "Rare"),
    JokerInfo(106, "Golden Ticket", 5, "Played Gold cards earn $4 when scored"),
    JokerInfo(107, "Mr. Bones", 5, "Prevents death if chips scored are at least 25% of required chips", "Uncommon"),
    JokerInfo(108, "Acrobat", 6, "X3 Mult on final hand of round", "Uncommon"),
    JokerInfo(109, "Sock & Buskin", 6, "Retrigger all played face cards", "Uncommon"),
    JokerInfo(110, "Swashbuckler", 4, "Sell value of all Jokers added to Mult"),
    JokerInfo(111, "Troubadour", 6, "+2 hand size, -1 hand per round", "Uncommon"),
    JokerInfo(112, "Certificate", 6, "When round begins, add a random playing card with a random seal to your hand", "Uncommon"),
    JokerInfo(113, "Smeared Joker", 7, "Hearts and Diamonds count as the same suit, Spades and Clubs count as the same suit", "Uncommon"),
    JokerInfo(114, "Throwback", 6, "Gains X0.25 Mult for each Blind skipped this run", "Uncommon"),
    JokerInfo(115, "Hanging Chad", 4, "Retrigger the first played card used in scoring 2 additional times"),
    JokerInfo(116, "Rough Gem", 7, "Played cards with Diamond suit earn $1 when scored", "Uncommon"),
    JokerInfo(117, "Bloodstone", 7, "1 in 2 chance for played cards with Heart suit to give X2 Mult", "Uncommon"),
    JokerInfo(118, "Arrowhead", 7, "Played cards with Spade suit give +50 Chips", "Uncommon"),
    JokerInfo(119, "Onyx Agate", 7, "Played cards with Club suit give +7 Mult", "Uncommon"),
    JokerInfo(120, "Glass Joker", 6, "Gains X0.75 Mult for every Glass card destroyed", "Uncommon"),
    JokerInfo(121, "Showman", 5, "Joker, Tarot, Planet, and Spectral cards may appear multiple times"),
    JokerInfo(122, "Flower Pot", 6, "X3 Mult if played hand contains all 4 suits", "Uncommon"),
    JokerInfo(123, "Blueprint", 10, "Copies ability of Joker to the right", "Rare"),
    JokerInfo(124, "Wee Joker", 8, "Each played 2 gives +8 Chips when scored", "Rare"),
    JokerInfo(125, "Merry Andy", 7, "+3 discards, -1 hand size", "Uncommon"),
    JokerInfo(126, "Oops! All 6s", 4, "Doubles all listed probabilities"),
    JokerInfo(127, "The Idol", 6, "Each played card of the randomly selected rank and suit gives X2 Mult", "Uncommon"),
    JokerInfo(128, "Seeing Double", 6, "X2 Mult if played hand contains a Club card and any other suit", "Uncommon"),
    JokerInfo(129, "Matador", 7, "Earn $8 if played hand triggers the Boss Blind ability", "Uncommon"),
    JokerInfo(130, "Hit the Road", 8, "Gains X0.5 Mult for each Jack discarded this round", "Rare"),
    JokerInfo(131, "The Duo", 8, "X2 Mult if hand contains a Pair", "Rare"),
    JokerInfo(132, "The Trio", 8, "X3 Mult if hand contains Three of a Kind", "Rare"),
    JokerInfo(133, "The Family", 8, "X4 Mult if hand contains Four of a Kind", "Rare"),
    JokerInfo(134, "The Order", 8, "X3 Mult if hand contains a Straight", "Rare"),
    JokerInfo(135, "The Tribe", 8, "X2 Mult if hand contains a Flush", "Rare"),
    JokerInfo(136, "Stuntman", 7, "+250 Chips, -2 hand size", "Uncommon"),
    JokerInfo(137, "Invisible Joker", 8, "After 2 rounds, sell this card to Duplicate a random Joker", "Rare"),
    JokerInfo(138, "Brainstorm", 10, "Copies ability of Joker to the left", "Rare"),
    JokerInfo(139, "Satellite", 6, "Earn $1 at end of round for each Planet card used this run", "Uncommon"),
    JokerInfo(140, "Shoot the Moon", 5, "Each Queen held in hand gives +13 Mult"),
    JokerInfo(141, "Driver's License", 7, "X3 Mult if you have at least 16 enhanced cards in your deck", "Rare"),
    JokerInfo(142, "Cartomancer", 6, "When Boss Blind is defeated, create a Tarot card", "Uncommon"),
    JokerInfo(143, "Astronomer", 8, "All Planet cards and Celestial Packs in the shop are free"),
    JokerInfo(144, "Burnt Joker", 8, "Upgrade the level of the first discarded poker hand of the round", "Rare"),
    JokerInfo(145, "Bootstraps", 7, "+2 Mult for every $5 you have", "Uncommon"),
    # Legendaries (cost = 0, found only in Spectral packs)
    JokerInfo(146, "Canio", 0, "Gains X1 Mult when a face card is destroyed", "Legendary"),
    JokerInfo(147, "Triboulet", 0, "Played Kings and Queens each give X2 Mult", "Legendary"),
    JokerInfo(148, "Yorick", 0, "Gains X1 Mult for every 23 cards discarded", "Legendary"),
    JokerInfo(149, "Chicot", 0, "Disables effect of every Boss Blind", "Legendary"),
    JokerInfo(150, "Perkeo", 0, "Creates a Negative copy of 1 random consumable card at end of shop", "Legendary"),
]

JOKER_ID_TO_INFO = {j.id: j for j in JOKER_LIBRARY}
JOKER_NAME_TO_ID = {j.name: j.id for j in JOKER_LIBRARY}
